# ConfigFile
server{
	server_name www.example.com example.com; # Space separated strings -> FORCE IF MULTIPLE SERVER
	listen 8090 8080 8080 8080 8080 8080; # Space separated ints -> FORCE
	index index.php index.html; # Space separated strings
	autoindex off;
	root /tests;
	client_max_body_size 1M; # (no case sensitive)
	method GET POST;
	upload_path /var/www/uploads;
	cgi .php /path/to/executable;

	location /api
	{
		root /var/www/html;
		cgi .php /path/to/executable; # No default
		autoindex off;
		index index.php index.html;
		client_max_body_size 10M;
		method GET POST;
		return 301 http://example.com;
		return 302 http://example.com;
		error_page 404 404.html;
		error_page 505 505.html;
	}

	location /apis
	{
		root /var/www/html;
		cgi .py /path/to/executable; # No default
	}
}

server{
	server_name www.example.com example.com; # Space separated strings -> FORCE IF MULTIPLE SERVER
	listen 8091 8081; # Space separated ints -> FORCE
	index index.php index.html; # Space separated strings
	autoindex off;
	root /tests;
	client_max_body_size 1M; # (no case sensitive)
	method GET POST;
	upload_path /var/www/uploads;
	cgi .php /path/to/executable;

	location /api
	{
		root /var/www/html;
		cgi .php /path/to/executable; # No default
		autoindex off;
		index index.php index.html;
		client_max_body_size 10M;
		method GET POST;
		return 301 http://example.com;
		return 302 http://example.com;
		error_page 404 404.html;
		error_page 505 505.html;
	}

	location /apis
	{
		root /var/www/html;
		cgi .py /path/to/executable; # No default
	}
}

